# coding: utf-8

"""
    p0_backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import json


# noinspection Mypy,DuplicatedCode
class (object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, send_midi):
        self._send_midi = send_midi

    def _send_dict_as_midi(self, dict):
        # type: (dict) -> None
        message = json.dumps(dict)
        b = bytearray(message.encode())
        b.insert(0, 0xF0)
        b.append(0xF7)
        self._send_midi(tuple(b))

    def actions_actions_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Actions  # noqa: E501
        """

        dict = {
            "method": "actions_actions_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def arm_arm_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Arm  # noqa: E501
        """

        dict = {
            "method": "arm_arm_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def bounce_track_to_audio_bounce_track_to_audio_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Bounce Track To Audio  # noqa: E501
        """

        dict = {
            "method": "bounce_track_to_audio_bounce_track_to_audio_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def check_audio_export_valid_check_audio_export_valid_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Check Audio Export Valid  # noqa: E501
        """

        dict = {
            "method": "check_audio_export_valid_check_audio_export_valid_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def click_focused_track_click_focused_track_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Click Focused Track  # noqa: E501
        """

        dict = {
            "method": "click_focused_track_click_focused_track_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def delete_saved_track_delete_saved_track_track_name_get(self, track_name, ):  # noqa: E501
        # type: (str, ) -> None
        """
             Delete Saved Track  # noqa: E501
        """

        dict = {
            "method": "delete_saved_track_delete_saved_track_track_name_get",
            "args": {
                "track_name": track_name, 
            }
        }

        self._send_dict_as_midi(dict)

    def delete_set_set_set_id_delete(self, set_id, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Delete Set  # noqa: E501
        """

        dict = {
            "method": "delete_set_set_set_id_delete",
            "args": {
                "set_id": set_id, 
            }
        }

        self._send_dict_as_midi(dict)

    def drag_matching_track_drag_matching_track_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Drag Matching Track  # noqa: E501
        """

        dict = {
            "method": "drag_matching_track_drag_matching_track_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def drum_rack_to_simpler_drum_rack_to_simpler_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Drum Rack To Simpler  # noqa: E501
        """

        dict = {
            "method": "drum_rack_to_simpler_drum_rack_to_simpler_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def edit_automation_value_edit_automation_value_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Edit Automation Value  # noqa: E501
        """

        dict = {
            "method": "edit_automation_value_edit_automation_value_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def execute_action_actions_group_id_action_id_get(self, group_id, action_id, ):  # noqa: E501
        # type: (int, int, ) -> None
        """
            Execute Action  # noqa: E501
        """

        dict = {
            "method": "execute_action_actions_group_id_action_id_get",
            "args": {
                "group_id": group_id, "action_id": action_id, 
            }
        }

        self._send_dict_as_midi(dict)

    def fire_scene_to_position_fire_scene_to_position_bar_length_get(self, bar_length, ):  # noqa: E501
        # type: (int, ) -> None
        """
            Fire Scene To Position  # noqa: E501
        """

        dict = {
            "method": "fire_scene_to_position_fire_scene_to_position_bar_length_get",
            "args": {
                "bar_length": bar_length, 
            }
        }

        self._send_dict_as_midi(dict)

    def fire_scene_to_position_fire_scene_to_position_get(self, bar_length=):  # noqa: E501
        # type: (int, ) -> None
        """
            Fire Scene To Position  # noqa: E501
        """

        dict = {
            "method": "fire_scene_to_position_fire_scene_to_position_get",
            "args": {
                "bar_length": bar_length, 
            }
        }

        self._send_dict_as_midi(dict)

    def fire_selected_scene_fire_selected_scene_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Fire Selected Scene  # noqa: E501
        """

        dict = {
            "method": "fire_selected_scene_fire_selected_scene_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def get_connections_ws_connections_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Get Connections  # noqa: E501
        """

        dict = {
            "method": "get_connections_ws_connections_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def go_to_group_track_go_to_group_track_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Go To Group Track  # noqa: E501
        """

        dict = {
            "method": "go_to_group_track_go_to_group_track_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def load_device_load_device_name_get(self, name, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Load Device  # noqa: E501
        """

        dict = {
            "method": "load_device_load_device_name_get",
            "args": {
                "name": name, 
            }
        }

        self._send_dict_as_midi(dict)

    def load_drum_rack_load_drum_rack_category_subcategory_get(self, category, subcategory, ):  # noqa: E501
        # type: (str, str, ) -> None
        """
            Load Drum Rack  # noqa: E501
        """

        dict = {
            "method": "load_drum_rack_load_drum_rack_category_subcategory_get",
            "args": {
                "category": category, "subcategory": subcategory, 
            }
        }

        self._send_dict_as_midi(dict)

    def load_matching_track_load_matching_track_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Load Matching Track  # noqa: E501
        """

        dict = {
            "method": "load_matching_track_load_matching_track_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def load_minitaur_load_minitaur_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Load Minitaur  # noqa: E501
        """

        dict = {
            "method": "load_minitaur_load_minitaur_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def load_rev2_load_rev2_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Load Rev2  # noqa: E501
        """

        dict = {
            "method": "load_rev2_load_rev2_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def open_set_set_name_open_get(self, name, ):  # noqa: E501
        # type: (str, ) -> None
        """
             Open Set  # noqa: E501
        """

        dict = {
            "method": "open_set_set_name_open_get",
            "args": {
                "name": name, 
            }
        }

        self._send_dict_as_midi(dict)

    def play_pause_play_pause_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Play Pause  # noqa: E501
        """

        dict = {
            "method": "play_pause_play_pause_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def post_set_set_post(self, ableton_set, ):  # noqa: E501
        # type: (AbletonSet, ) -> None
        """
            Post Set  # noqa: E501
        """

        dict = {
            "method": "post_set_set_post",
            "args": {
                "ableton_set": ableton_set, 
            }
        }

        self._send_dict_as_midi(dict)

    def record_unlimited_record_unlimited_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Record Unlimited  # noqa: E501
        """

        dict = {
            "method": "record_unlimited_record_unlimited_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def reload_ableton_reload_ableton_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Reload Ableton  # noqa: E501
        """

        dict = {
            "method": "reload_ableton_reload_ableton_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def reload_script_reload_script_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Reload Script  # noqa: E501
        """

        dict = {
            "method": "reload_script_reload_script_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def save_set_as_template_save_set_as_template_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Save Set As Template  # noqa: E501
        """

        dict = {
            "method": "save_set_as_template_save_set_as_template_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def save_track_to_sub_tracks_save_track_to_sub_tracks_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Save Track To Sub Tracks  # noqa: E501
        """

        dict = {
            "method": "save_track_to_sub_tracks_save_track_to_sub_tracks_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def scroll_scene_position_fine_scroll_scene_position_fine_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Scroll Scene Position Fine  # noqa: E501
        """

        dict = {
            "method": "scroll_scene_position_fine_scroll_scene_position_fine_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def scroll_scene_position_scroll_scene_position_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Scroll Scene Position  # noqa: E501
        """

        dict = {
            "method": "scroll_scene_position_scroll_scene_position_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def scroll_scene_tracks_scroll_scene_tracks_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Scroll Scene Tracks  # noqa: E501
        """

        dict = {
            "method": "scroll_scene_tracks_scroll_scene_tracks_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def scroll_scenes_scroll_scenes_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Scroll Scenes  # noqa: E501
        """

        dict = {
            "method": "scroll_scenes_scroll_scenes_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def scroll_track_volume_scroll_track_volume_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Scroll Track Volume  # noqa: E501
        """

        dict = {
            "method": "scroll_track_volume_scroll_track_volume_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def select_or_load_device_select_or_load_device_name_get(self, name, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Select Or Load Device  # noqa: E501
        """

        dict = {
            "method": "select_or_load_device_select_or_load_device_name_get",
            "args": {
                "name": name, 
            }
        }

        self._send_dict_as_midi(dict)

    def server_state_server_state_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Server State  # noqa: E501
        """

        dict = {
            "method": "server_state_server_state_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def show_automation_show_automation_direction_get(self, direction, ):  # noqa: E501
        # type: (str, ) -> None
        """
            Show Automation  # noqa: E501
        """

        dict = {
            "method": "show_automation_show_automation_direction_get",
            "args": {
                "direction": direction, 
            }
        }

        self._send_dict_as_midi(dict)

    def show_instrument_show_instrument_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Show Instrument  # noqa: E501
        """

        dict = {
            "method": "show_instrument_show_instrument_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def show_saved_tracks_show_saved_tracks_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Show Saved Tracks  # noqa: E501
        """

        dict = {
            "method": "show_saved_tracks_show_saved_tracks_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def tail_logs_raw_tail_logs_raw_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Tail Logs Raw  # noqa: E501
        """

        dict = {
            "method": "tail_logs_raw_tail_logs_raw_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def tail_logs_tail_logs_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Tail Logs  # noqa: E501
        """

        dict = {
            "method": "tail_logs_tail_logs_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def test_test_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Test  # noqa: E501
        """

        dict = {
            "method": "test_test_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def toggle_clip_notes_toggle_clip_notes_get(self, ):  # noqa: E501
        # type: () -> None
        """
             Toggle Clip Notes  # noqa: E501
        """

        dict = {
            "method": "toggle_clip_notes_toggle_clip_notes_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def toggle_reference_toggle_reference_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Toggle Reference  # noqa: E501
        """

        dict = {
            "method": "toggle_reference_toggle_reference_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def toggle_scene_loop_toggle_scene_loop_get(self, ):  # noqa: E501
        # type: () -> None
        """
            Toggle Scene Loop  # noqa: E501
        """

        dict = {
            "method": "toggle_scene_loop_toggle_scene_loop_get",
            "args": {
                
            }
        }

        self._send_dict_as_midi(dict)

    def update_set_set_put(self, title, path=):  # noqa: E501
        # type: (str, str, ) -> None
        """
            Update Set  # noqa: E501
        """

        dict = {
            "method": "update_set_set_put",
            "args": {
                "title": title, "path": path, 
            }
        }

        self._send_dict_as_midi(dict)
