# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec of the Protocol0 launcher (the "shortcut" the user clicks).
#
# Build: from src/agent,  poetry run pyinstaller --clean --noconfirm protocol0-launcher.spec
# Output: dist/protocol0-launcher.exe
#
# Role: open http://127.0.0.1:9010/ (the page served by the resident agent) in the default
# browser, then exit. See agent/launcher_entry.py for why a dedicated exe rather than an
# Internet shortcut (.url): it carries its own icon (the "P" badge) and has no shortcut
# overlay arrow once dropped on the desktop.
#
# Notes:
# - icon: installer/assets/protocol0.ico, generated by scripts/windows/generate_icon.py
#   (MUST exist before this build; build_installer.ps1 calls it beforehand).
# - console=False (--windowed): no console flash on open.
# - upx=False: consistent with the agent (UPX compression triggers AV false positives).
# - Tiny exe: only webbrowser (stdlib) + agent.settings (for the port) are pulled in.

block_cipher = None

a = Analysis(
    ['agent\\launcher_entry.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='protocol0-launcher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='..\\..\\installer\\assets\\protocol0.ico',
)
