"""Coverage report of the @action catalog against the LOM inventory.

Joins lom-inventory.json (generated by extract.py) with catalog-map.json (hand
curated) and the ableton-mcp checklist (the 24 commands of the reference MCP
remote script + the known blind spots), and writes docs/lom/coverage.md.

Exit code 1 if the map references unknown op ids (typo guard). The "every
checklist item exposed or waived" gate is a pytest meta-test added at catalog
closeout, not enforced here.
"""
import json
import sys
from pathlib import Path

DOCS_LOM = Path(__file__).resolve().parents[2] / "docs" / "lom"

# ableton-mcp parity checklist: each item lists the inventory ops it needs
# exposed, or carries a waiver. Read surface (get_*) rides on the state
# endpoint, enriched in the arrangement/state phase.
_STATE_WAIVER = "read surface: served by GET /api/set/get_state (enriched in the state phase)"
_BROWSER_WAIVER = "browser navigation deferred: v1 loads by name only (DeviceService)"

CHECKLIST = {
    "get_session_info": {"waived": _STATE_WAIVER},
    "get_session_snapshot": {"waived": _STATE_WAIVER},
    "get_track_info": {"waived": _STATE_WAIVER},
    "get_arrangement_clips": {"waived": _STATE_WAIVER},
    "get_clip_notes": {"waived": _STATE_WAIVER},
    "get_device_parameters": {"waived": _STATE_WAIVER},
    "get_browser_tree": {"waived": _BROWSER_WAIVER},
    "get_browser_items_at_path": {"waived": _BROWSER_WAIVER},
    "create_midi_track": {"ops": ["Song.create_midi_track"]},
    "create_audio_track": {"ops": ["Song.create_audio_track"]},
    "create_clip": {"ops": ["ClipSlot.create_clip"]},
    "create_audio_clip": {
        "waived": "audio clip creation needs a sample file path: deferred with browser navigation"
    },
    "delete_clip": {"ops": ["ClipSlot.delete_clip"]},
    "duplicate_to_arrangement": {"ops": ["Track.duplicate_clip_to_arrangement"]},
    "create_locator": {"ops": ["Song.set_or_delete_cue"]},
    "set_arrangement_time": {"ops": ["Song.current_song_time"]},
    "set_arrangement_clip_name": {"ops": ["Clip.name"]},
    "set_clip_name": {"ops": ["Clip.name"]},
    "set_track_name": {"ops": ["Track.name"]},
    "set_tempo": {"ops": ["Song.tempo"]},
    "set_device_parameter": {"ops": ["DeviceParameter.value"]},
    "fire_clip": {"ops": ["Clip.fire"]},
    "stop_clip": {"ops": ["Clip.stop"]},
    "start_playback": {"ops": ["Song.start_playing"]},
    "stop_playback": {"ops": ["Song.stop_playing"]},
    "add_notes_to_clip": {"ops": ["Clip.add_new_notes"]},
    "clear_notes_from_clip": {"ops": ["Clip.remove_notes_extended"]},
    "load_instrument_or_effect": {"ops": ["Browser.load_item"]},
    "load_drum_kit": {"ops": ["Browser.load_item"]},
    "switch_to_arrangement_view": {"ops": ["Application.View.show_view"]},
}


def _all_op_ids(inventory: dict) -> set:
    ids = set()
    for class_key, content in inventory["classes"].items():
        for prop in content["properties"]:
            ids.add("%s.%s" % (class_key, prop["name"]))
        for method in content["methods"]:
            ids.add("%s.%s" % (class_key, method["name"]))
    return ids


def _class_rows(inventory: dict, ops: dict) -> list:
    rows = []
    for class_key, content in sorted(inventory["classes"].items()):
        exposable = [m for m in content["methods"] if m["actionable"]] + [
            p for p in content["properties"] if p["settable"]
        ]
        if not exposable:
            continue
        statuses = {"exposed": 0, "domain-only": 0, "skipped": 0, "todo": 0}
        for member in exposable:
            op = ops.get("%s.%s" % (class_key, member["name"]))
            statuses[op["status"] if op else "todo"] += 1
        rows.append((class_key, len(exposable), statuses))
    return rows


def main() -> int:
    inventory = json.loads((DOCS_LOM / "lom-inventory.json").read_text(encoding="utf-8"))
    catalog_map = json.loads((DOCS_LOM / "catalog-map.json").read_text(encoding="utf-8"))
    ops = catalog_map["ops"]

    known_ids = _all_op_ids(inventory)
    unknown = sorted(set(ops) - known_ids)
    for checklist_item in CHECKLIST.values():
        unknown += sorted(set(checklist_item.get("ops", [])) - known_ids)
    if unknown:
        print("unknown op ids (typo?): %s" % ", ".join(unknown))
        return 1

    exposed = {op_id for op_id, op in ops.items() if op["status"] == "exposed"}
    lines = [
        "# Action catalog coverage",
        "",
        "Generated by `python scripts/lom_catalog/coverage.py` — do not edit.",
        "",
        "## ableton-mcp parity checklist",
        "",
        "| command | status | detail |",
        "|---|---|---|",
    ]
    checklist_done = 0
    for name, item in CHECKLIST.items():
        if "waived" in item:
            status, detail = "waived", item["waived"]
            checklist_done += 1
        elif set(item["ops"]) <= exposed:
            status, detail = "exposed", ", ".join(item["ops"])
            checklist_done += 1
        else:
            missing = sorted(set(item["ops"]) - exposed)
            status, detail = "todo", "missing: " + ", ".join(missing)
        lines.append("| %s | %s | %s |" % (name, status, detail))
    lines += [
        "",
        "**%d/%d** checklist items exposed or waived." % (checklist_done, len(CHECKLIST)),
        "",
        "## Per-class exposure (actionable methods + settable properties)",
        "",
        "| class | exposable | exposed | domain-only | skipped | todo |",
        "|---|---|---|---|---|---|",
    ]
    for class_key, exposable_count, statuses in _class_rows(inventory, ops):
        lines.append(
            "| %s | %d | %d | %d | %d | %d |"
            % (
                class_key,
                exposable_count,
                statuses["exposed"],
                statuses["domain-only"],
                statuses["skipped"],
                statuses["todo"],
            )
        )

    output = DOCS_LOM / "coverage.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("%s: checklist %d/%d" % (output, checklist_done, len(CHECKLIST)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
