version: '3.4'

services:
  backend:
    build:
      context: .
      target: "development"
#    image: "p0-backend:development"
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: poetry run http-server
#    volumes:
#      - ./:/app
