//! HTTP client to the remote script's API — mirror of agent/script_client.py.
//!
//! The agent just replaces AHK as an event producer: the action API exposed by the script is
//! unchanged.
//!
//! The base URL is resolved ON EACH CALL, not once: the agent lives from logon to logoff,
//! while Ableton (and its server, on a dynamic port) starts/stops several times in between.
//! So we read the current URL from P0_SCRIPT_PORT (override) or runtime.json on each binding
//! execution; absence = script not active = no-op.

use crate::config::Binding;
use crate::settings::Settings;
use crate::{action_catalog, runtime_state};

pub struct ScriptClient {
    settings: Settings,
    client: reqwest::blocking::Client,
}

impl ScriptClient {
    pub fn new(settings: Settings) -> Self {
        Self {
            settings,
            client: reqwest::blocking::Client::new(),
        }
    }

    fn resolve_base_url(&self) -> Option<String> {
        // 1) manual override (P0_SCRIPT_PORT); 2) discovery via runtime.json; 3) None.
        if let Some(url) = self.settings.override_url() {
            return Some(url);
        }
        runtime_state::read().map(|rt| rt.script_url)
    }

    /// Generic dispatch: resolve the action in the catalog the script exposes (its
    /// /openapi.json) at trigger time, then POST to its route. No action is hardcoded —
    /// dropping an `@action` plugin is enough to make it executable. (`send_keys` never
    /// reaches here: it's injected locally upstream, see main.rs.)
    pub fn execute(&self, binding: &Binding) {
        let Some(base_url) = self.resolve_base_url() else {
            tracing::info!("script not running, ignoring {}", binding.combo);
            return;
        };

        let catalog = action_catalog::fetch(&base_url, &self.client);
        let Some(action) = catalog.iter().find(|a| a.name == binding.action) else {
            tracing::warn!("unknown action: {}", binding.action);
            return;
        };

        // Body = the params the action declares, taken from the binding (missing -> omitted;
        // the script returns 400 if a required one is absent, which post() logs).
        let body: serde_json::Map<String, serde_json::Value> = action
            .params
            .iter()
            .filter_map(|p| {
                binding
                    .params
                    .get(&p.name)
                    .map(|v| (p.name.clone(), serde_json::Value::String(v.clone())))
            })
            .collect();

        // Mutation -> POST under /api (REST: GET reads, POST mutates), args as JSON body. The
        // /action/<plugin>/<method> route is generated by the plugin via @action.
        let path = format!("/api{}", action.path);
        self.post(&base_url, &path, serde_json::Value::Object(body));
    }

    fn post(&self, base_url: &str, path: &str, body: serde_json::Value) {
        let url = format!("{base_url}{path}");
        let result = self
            .client
            .post(&url)
            .json(&body)
            .timeout(std::time::Duration::from_secs(5))
            .send()
            .and_then(|r| r.error_for_status());
        if let Err(e) = result {
            tracing::warn!("script HTTP {path} failed: {e}");
        }
    }
}
