from enum import Enum


class SongDataEnum(Enum):
    SELECTED_SCENE_INDEX = "SELECTED_SCENE_INDEX"
    SELECTED_SCENE_POSITION = "SELECTED_SCENE_POSITION"
    SELECTED_TRACK_INDEX = "SELECTED_TRACK_INDEX"
