# coding: utf-8

"""
    P0 backend Client

    P0 backend Client  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import p0_backend_client
from p0_backend_client.api.default_api import DefaultApi  # noqa: E501
from p0_backend_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = p0_backend_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_rev2_editor(self):
        """Test case for activate_rev2_editor

        """
        pass

    def test_analyze_test_audio_clip_jitter(self):
        """Test case for analyze_test_audio_clip_jitter

        """
        pass

    def test_clear_arrangement(self):
        """Test case for clear_arrangement

        """
        pass

    def test_click(self):
        """Test case for click

        """
        pass

    def test_click_focused_track(self):
        """Test case for click_focused_track

        """
        pass

    def test_click_vertical_zone(self):
        """Test case for click_vertical_zone

        """
        pass

    def test_close_explorer_window(self):
        """Test case for close_explorer_window

        """
        pass

    def test_close_samples_windows(self):
        """Test case for close_samples_windows

        """
        pass

    def test_close_set(self):
        """Test case for close_set

        """
        pass

    def test_crop_clip(self):
        """Test case for crop_clip

        """
        pass

    def test_delete_saved_track(self):
        """Test case for delete_saved_track

        """
        pass

    def test_drag_matching_track(self):
        """Test case for drag_matching_track

        """
        pass

    def test_flatten_track(self):
        """Test case for flatten_track

        """
        pass

    def test_hide_plugins(self):
        """Test case for hide_plugins

        """
        pass

    def test_load_instrument_track(self):
        """Test case for load_instrument_track

        """
        pass

    def test_load_sample_in_simpler(self):
        """Test case for load_sample_in_simpler

        """
        pass

    def test_move_to(self):
        """Test case for move_to

        """
        pass

    def test_notify_set_state(self):
        """Test case for notify_set_state

        """
        pass

    def test_ping(self):
        """Test case for ping

        """
        pass

    def test_post_activate_rev2_editor(self):
        """Test case for post_activate_rev2_editor

        """
        pass

    def test_reload_ableton(self):
        """Test case for reload_ableton

        """
        pass

    def test_save_set(self):
        """Test case for save_set

        """
        pass

    def test_save_track_to_sub_tracks(self):
        """Test case for save_track_to_sub_tracks

        """
        pass

    def test_search(self):
        """Test case for search

        """
        pass

    def test_select(self):
        """Test case for select

        """
        pass

    def test_select_and_copy(self):
        """Test case for select_and_copy

        """
        pass

    def test_select_and_paste(self):
        """Test case for select_and_paste

        """
        pass

    def test_set_clip_file_path(self):
        """Test case for set_clip_file_path

        """
        pass

    def test_set_envelope_loop_length(self):
        """Test case for set_envelope_loop_length

        """
        pass

    def test_show_error(self):
        """Test case for show_error

        """
        pass

    def test_show_hide_plugins(self):
        """Test case for show_hide_plugins

        """
        pass

    def test_show_info(self):
        """Test case for show_info

        """
        pass

    def test_show_plugins(self):
        """Test case for show_plugins

        """
        pass

    def test_show_sample_category(self):
        """Test case for show_sample_category

        """
        pass

    def test_show_saved_tracks(self):
        """Test case for show_saved_tracks

        """
        pass

    def test_show_success(self):
        """Test case for show_success

        """
        pass

    def test_show_warning(self):
        """Test case for show_warning

        """
        pass

    def test_start_profiling_single_measurement(self):
        """Test case for start_profiling_single_measurement

        """
        pass

    def test_start_set_profiling(self):
        """Test case for start_set_profiling

        """
        pass

    def test_stop_midi_server(self):
        """Test case for stop_midi_server

        """
        pass

    def test_tail_logs(self):
        """Test case for tail_logs

        """
        pass

    def test_toggle_ableton_button(self):
        """Test case for toggle_ableton_button

        """
        pass


if __name__ == '__main__':
    unittest.main()
