# coding: utf-8

"""
    p0_backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import p0_backend_client
from p0_backend_client.models.ableton_track import AbletonTrack  # noqa: E501
from p0_backend_client.rest import ApiException

class TestAbletonTrack(unittest.TestCase):
    """AbletonTrack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AbletonTrack
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = p0_backend_client.models.ableton_track.AbletonTrack()  # noqa: E501
        if include_optional :
            return AbletonTrack(
                name = '', 
                type = '', 
                index = 56
            )
        else :
            return AbletonTrack(
                name = '',
                type = '',
                index = 56,
        )

    def testAbletonTrack(self):
        """Test AbletonTrack"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
