# coding: utf-8

"""
    p0_backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import p0_backend_client
from p0_backend_client.api.default_api import DefaultApi  # noqa: E501
from p0_backend_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = p0_backend_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actions_actions_get(self):
        """Test case for actions_actions_get

        Actions  # noqa: E501
        """
        pass

    def test_arm_arm_get(self):
        """Test case for arm_arm_get

        Arm  # noqa: E501
        """
        pass

    def test_bounce_track_to_audio_bounce_track_to_audio_get(self):
        """Test case for bounce_track_to_audio_bounce_track_to_audio_get

         Bounce Track To Audio  # noqa: E501
        """
        pass

    def test_check_audio_export_valid_check_audio_export_valid_get(self):
        """Test case for check_audio_export_valid_check_audio_export_valid_get

        Check Audio Export Valid  # noqa: E501
        """
        pass

    def test_click_focused_track_click_focused_track_get(self):
        """Test case for click_focused_track_click_focused_track_get

         Click Focused Track  # noqa: E501
        """
        pass

    def test_delete_saved_track_delete_saved_track_track_name_get(self):
        """Test case for delete_saved_track_delete_saved_track_track_name_get

         Delete Saved Track  # noqa: E501
        """
        pass

    def test_delete_set_set_set_id_delete(self):
        """Test case for delete_set_set_set_id_delete

        Delete Set  # noqa: E501
        """
        pass

    def test_drag_matching_track_drag_matching_track_get(self):
        """Test case for drag_matching_track_drag_matching_track_get

         Drag Matching Track  # noqa: E501
        """
        pass

    def test_drum_rack_to_simpler_drum_rack_to_simpler_get(self):
        """Test case for drum_rack_to_simpler_drum_rack_to_simpler_get

        Drum Rack To Simpler  # noqa: E501
        """
        pass

    def test_edit_automation_value_edit_automation_value_get(self):
        """Test case for edit_automation_value_edit_automation_value_get

         Edit Automation Value  # noqa: E501
        """
        pass

    def test_execute_action_actions_group_id_action_id_get(self):
        """Test case for execute_action_actions_group_id_action_id_get

        Execute Action  # noqa: E501
        """
        pass

    def test_fire_scene_to_position_fire_scene_to_position_bar_length_get(self):
        """Test case for fire_scene_to_position_fire_scene_to_position_bar_length_get

        Fire Scene To Position  # noqa: E501
        """
        pass

    def test_fire_scene_to_position_fire_scene_to_position_get(self):
        """Test case for fire_scene_to_position_fire_scene_to_position_get

        Fire Scene To Position  # noqa: E501
        """
        pass

    def test_fire_selected_scene_fire_selected_scene_get(self):
        """Test case for fire_selected_scene_fire_selected_scene_get

        Fire Selected Scene  # noqa: E501
        """
        pass

    def test_get_connections_ws_connections_get(self):
        """Test case for get_connections_ws_connections_get

        Get Connections  # noqa: E501
        """
        pass

    def test_go_to_group_track_go_to_group_track_get(self):
        """Test case for go_to_group_track_go_to_group_track_get

         Go To Group Track  # noqa: E501
        """
        pass

    def test_load_device_load_device_name_get(self):
        """Test case for load_device_load_device_name_get

        Load Device  # noqa: E501
        """
        pass

    def test_load_drum_rack_load_drum_rack_category_subcategory_get(self):
        """Test case for load_drum_rack_load_drum_rack_category_subcategory_get

        Load Drum Rack  # noqa: E501
        """
        pass

    def test_load_matching_track_load_matching_track_get(self):
        """Test case for load_matching_track_load_matching_track_get

        Load Matching Track  # noqa: E501
        """
        pass

    def test_load_minitaur_load_minitaur_get(self):
        """Test case for load_minitaur_load_minitaur_get

        Load Minitaur  # noqa: E501
        """
        pass

    def test_load_rev2_load_rev2_get(self):
        """Test case for load_rev2_load_rev2_get

        Load Rev2  # noqa: E501
        """
        pass

    def test_open_set_set_name_open_get(self):
        """Test case for open_set_set_name_open_get

         Open Set  # noqa: E501
        """
        pass

    def test_play_pause_play_pause_get(self):
        """Test case for play_pause_play_pause_get

        Play Pause  # noqa: E501
        """
        pass

    def test_post_set_set_post(self):
        """Test case for post_set_set_post

        Post Set  # noqa: E501
        """
        pass

    def test_record_unlimited_record_unlimited_get(self):
        """Test case for record_unlimited_record_unlimited_get

        Record Unlimited  # noqa: E501
        """
        pass

    def test_reload_ableton_reload_ableton_get(self):
        """Test case for reload_ableton_reload_ableton_get

         Reload Ableton  # noqa: E501
        """
        pass

    def test_reload_script_reload_script_get(self):
        """Test case for reload_script_reload_script_get

         Reload Script  # noqa: E501
        """
        pass

    def test_save_set_as_template_save_set_as_template_get(self):
        """Test case for save_set_as_template_save_set_as_template_get

         Save Set As Template  # noqa: E501
        """
        pass

    def test_save_track_to_sub_tracks_save_track_to_sub_tracks_get(self):
        """Test case for save_track_to_sub_tracks_save_track_to_sub_tracks_get

         Save Track To Sub Tracks  # noqa: E501
        """
        pass

    def test_scroll_scene_position_fine_scroll_scene_position_fine_direction_get(self):
        """Test case for scroll_scene_position_fine_scroll_scene_position_fine_direction_get

        Scroll Scene Position Fine  # noqa: E501
        """
        pass

    def test_scroll_scene_position_scroll_scene_position_direction_get(self):
        """Test case for scroll_scene_position_scroll_scene_position_direction_get

        Scroll Scene Position  # noqa: E501
        """
        pass

    def test_scroll_scene_tracks_scroll_scene_tracks_direction_get(self):
        """Test case for scroll_scene_tracks_scroll_scene_tracks_direction_get

        Scroll Scene Tracks  # noqa: E501
        """
        pass

    def test_scroll_scenes_scroll_scenes_direction_get(self):
        """Test case for scroll_scenes_scroll_scenes_direction_get

        Scroll Scenes  # noqa: E501
        """
        pass

    def test_scroll_track_volume_scroll_track_volume_direction_get(self):
        """Test case for scroll_track_volume_scroll_track_volume_direction_get

        Scroll Track Volume  # noqa: E501
        """
        pass

    def test_select_or_load_device_select_or_load_device_name_get(self):
        """Test case for select_or_load_device_select_or_load_device_name_get

        Select Or Load Device  # noqa: E501
        """
        pass

    def test_server_state_server_state_get(self):
        """Test case for server_state_server_state_get

        Server State  # noqa: E501
        """
        pass

    def test_show_automation_show_automation_direction_get(self):
        """Test case for show_automation_show_automation_direction_get

        Show Automation  # noqa: E501
        """
        pass

    def test_show_instrument_show_instrument_get(self):
        """Test case for show_instrument_show_instrument_get

        Show Instrument  # noqa: E501
        """
        pass

    def test_show_saved_tracks_show_saved_tracks_get(self):
        """Test case for show_saved_tracks_show_saved_tracks_get

         Show Saved Tracks  # noqa: E501
        """
        pass

    def test_tail_logs_raw_tail_logs_raw_get(self):
        """Test case for tail_logs_raw_tail_logs_raw_get

        Tail Logs Raw  # noqa: E501
        """
        pass

    def test_tail_logs_tail_logs_get(self):
        """Test case for tail_logs_tail_logs_get

        Tail Logs  # noqa: E501
        """
        pass

    def test_test_test_get(self):
        """Test case for test_test_get

        Test  # noqa: E501
        """
        pass

    def test_toggle_clip_notes_toggle_clip_notes_get(self):
        """Test case for toggle_clip_notes_toggle_clip_notes_get

         Toggle Clip Notes  # noqa: E501
        """
        pass

    def test_toggle_reference_toggle_reference_get(self):
        """Test case for toggle_reference_toggle_reference_get

        Toggle Reference  # noqa: E501
        """
        pass

    def test_toggle_scene_loop_toggle_scene_loop_get(self):
        """Test case for toggle_scene_loop_toggle_scene_loop_get

        Toggle Scene Loop  # noqa: E501
        """
        pass

    def test_update_set_set_put(self):
        """Test case for update_set_set_put

        Update Set  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
