version: '3.4'

services:
  backend:
    build:
      context: backend
      target: builder
    image: "thibaultlebrun/p0_web_backend"

  frontend:
    build:
      context: frontend
    image: "thibaultlebrun/p0_web_frontend"
